/* ════════════════════════════════════════════════════════════════
   COMPARE PAGES WE LET GOOGLE INDEX — the demand-proven allowlist.

   The /intelligence/compare/<a>-vs-<b> set is combinatorial (~4,656
   possible pairs for 97 projects); indexing all of them is thin-content
   that Google collapses as duplicate and that dilutes the site's quality
   signal. So the pair pages are noindex by default (see the compare route).

   This is the exception list: pairs that ALREADY earned search impressions
   in Google Search Console (Performance → Pages export, Aug 2026, ≥1
   impression) AND are actually built. These have demonstrated demand, so
   they earn their index slot. Everything else stays noindex + out of the
   sitemap. Refresh this list from a newer GSC export as demand shifts.
   A leaf module — imported by the compare route (index flag) and the
   sitemap. ════════════════════════════════════════════════════════════ */
export const INDEXABLE_COMPARE_PAIRS: ReadonlySet<string> = new Set([
  "ashiana-aaroham-phase-1-vs-ashiana-amarah-phase-5",
  "ashiana-aaroham-phase-1-vs-dlf-privana-south",
  "ashiana-aaroham-phase-1-vs-dlf-privana-west",
  "ashiana-aaroham-phase-2-vs-ashiana-amarah-phase-1-1a",
  "ashiana-aaroham-phase-2-vs-ashiana-amarah-phase-5",
  "ashiana-aaroham-phase-2-vs-dlf-gardencity-enclave-phase-1",
  "ashiana-aaroham-phase-2-vs-dlf-privana-south",
  "ashiana-aaroham-phase-2-vs-dlf-the-arbour",
  "ashiana-aaroham-phase-2-vs-m3m-altitude",
  "ashiana-aaroham-phase-2-vs-m3m-capital-phase-2",
  "ashiana-aaroham-phase-2-vs-oberoi-realty-360-north",
  "ashiana-aaroham-phase-2-vs-puri-diplomatic-residences",
  "ashiana-aaroham-phase-2-vs-smartworld-one-dxp-phase-2",
  "ashiana-amarah-phase-1-1a-vs-ashiana-amarah-phase-5",
  "ashiana-amarah-phase-1-1a-vs-dlf-gardencity-enclave-phase-2",
  "ashiana-amarah-phase-3-3a-vs-dlf-gardencity-enclave-phase-2",
  "ashiana-amarah-phase-3-3a-vs-m3m-altitude",
  "ashiana-amarah-phase-3-3a-vs-m3m-crown-phase-1",
  "ashiana-amarah-phase-4-vs-dlf-privana-south",
  "ashiana-amarah-phase-4-vs-emaar-amaris",
  "ashiana-amarah-phase-4-vs-m3m-golf-hills-phase-1",
  "ashiana-amarah-phase-4-vs-smartworld-sky-arc",
  "ashiana-amarah-phase-4-vs-sobha-city-phase-5",
  "ashiana-anmol-phase-3-vs-dlf-the-dahlias",
  "ashiana-anmol-phase-3-vs-smartworld-one-dxp-phase-2",
  "dlf-gardencity-enclave-phase-1-vs-dlf-privana-west",
  "dlf-gardencity-enclave-phase-1-vs-emaar-amaris",
  "dlf-gardencity-enclave-phase-1-vs-emaar-urban-oasis-phase-1-2",
  "dlf-gardencity-enclave-phase-1-vs-m3m-capital-phase-2",
  "dlf-gardencity-enclave-phase-1-vs-m3m-crown-phase-1",
  "dlf-gardencity-enclave-phase-1-vs-m3m-golf-hills-phase-2",
  "dlf-gardencity-enclave-phase-1-vs-m3m-mansion-phase-1",
  "dlf-gardencity-enclave-phase-1-vs-m3m-trump-towers-1",
  "dlf-gardencity-enclave-phase-1-vs-smartworld-one-dxp-phase-2",
  "dlf-gardencity-enclave-phase-2-vs-dlf-the-dahlias",
  "dlf-gardencity-enclave-phase-2-vs-elan-the-presidential",
  "dlf-privana-north-vs-dlf-privana-south",
  "dlf-privana-north-vs-dlf-privana-west",
  "dlf-privana-north-vs-dlf-the-arbour",
  "dlf-privana-north-vs-dlf-the-dahlias",
  "dlf-privana-north-vs-elan-the-emperor",
  "dlf-privana-north-vs-emaar-amaris",
  "dlf-privana-north-vs-emaar-the-88",
  "dlf-privana-north-vs-m3m-altitude",
  "dlf-privana-north-vs-m3m-trump-towers-1",
  "dlf-privana-north-vs-puri-diplomatic-residences",
  "dlf-privana-north-vs-smartworld-sky-arc",
  "dlf-privana-south-vs-dlf-privana-west",
  "dlf-privana-south-vs-dlf-the-arbour",
  "dlf-privana-south-vs-dlf-the-dahlias",
  "dlf-privana-south-vs-elan-the-emperor",
  "dlf-privana-south-vs-elan-the-presidential",
  "dlf-privana-south-vs-elan-the-statement",
  "dlf-privana-south-vs-emaar-the-88",
  "dlf-privana-south-vs-m3m-altitude",
  "dlf-privana-south-vs-m3m-golf-hills-phase-1",
  "dlf-privana-south-vs-m3m-golf-hills-phase-2",
  "dlf-privana-south-vs-oberoi-realty-360-north",
  "dlf-privana-south-vs-puri-diplomatic-residences",
  "dlf-privana-south-vs-puri-the-aravallis",
  "dlf-privana-south-vs-signature-global-titanium-spr",
  "dlf-privana-south-vs-sobha-city-phase-6",
  "dlf-privana-west-vs-dlf-the-arbour",
  "dlf-privana-west-vs-dlf-the-dahlias",
  "dlf-privana-west-vs-elan-the-presidential",
  "dlf-privana-west-vs-emaar-the-88",
  "dlf-privana-west-vs-oberoi-realty-360-north",
  "dlf-privana-west-vs-smartworld-sky-arc",
  "dlf-the-arbour-vs-dlf-the-dahlias",
  "dlf-the-arbour-vs-elan-the-presidential",
  "dlf-the-arbour-vs-emaar-amaris",
  "dlf-the-arbour-vs-emaar-the-88",
  "dlf-the-arbour-vs-m3m-altitude",
  "dlf-the-arbour-vs-m3m-crown-phase-1",
  "dlf-the-arbour-vs-m3m-golf-hills-phase-1",
  "dlf-the-arbour-vs-oberoi-realty-360-north",
  "dlf-the-arbour-vs-puri-the-aravallis",
  "dlf-the-arbour-vs-sobha-city-phase-5",
  "dlf-the-dahlias-vs-elan-the-presidential",
  "dlf-the-dahlias-vs-elan-the-statement",
  "dlf-the-dahlias-vs-emaar-the-88",
  "dlf-the-dahlias-vs-emaar-urban-oasis-phase-1-2",
  "dlf-the-dahlias-vs-m3m-altitude",
  "dlf-the-dahlias-vs-oberoi-realty-360-north",
  "elan-the-emperor-vs-elan-the-presidential",
  "elan-the-emperor-vs-elan-the-statement",
  "elan-the-emperor-vs-emaar-the-88",
  "elan-the-emperor-vs-oberoi-realty-360-north",
  "elan-the-emperor-vs-puri-diplomatic-residences",
  "elan-the-emperor-vs-smartworld-sky-arc",
  "elan-the-presidential-vs-emaar-amaris",
  "elan-the-presidential-vs-emaar-the-88",
  "elan-the-presidential-vs-m3m-altitude",
  "elan-the-presidential-vs-m3m-capital-phase-2",
  "elan-the-presidential-vs-oberoi-realty-360-north",
  "elan-the-presidential-vs-puri-diplomatic-residences",
  "elan-the-presidential-vs-puri-the-aravallis",
  "elan-the-presidential-vs-signature-global-titanium-spr",
  "elan-the-presidential-vs-smartworld-one-dxp-phase-2",
  "elan-the-presidential-vs-smartworld-sky-arc",
  "elan-the-statement-vs-emaar-amaris",
  "elan-the-statement-vs-m3m-altitude",
  "elan-the-statement-vs-m3m-golf-hills-phase-1",
  "elan-the-statement-vs-m3m-mansion-phase-1",
  "elan-the-statement-vs-smartworld-one-dxp",
  "emaar-amaris-vs-emaar-the-88",
  "emaar-amaris-vs-emaar-urban-oasis-phase-1-2",
  "emaar-amaris-vs-m3m-altitude",
  "emaar-amaris-vs-puri-the-aravallis",
  "emaar-amaris-vs-signature-global-titanium-spr",
  "emaar-amaris-vs-smartworld-one-dxp",
  "emaar-amaris-vs-smartworld-sky-arc",
  "emaar-amaris-vs-sobha-city-phase-6",
  "emaar-the-88-vs-m3m-capital-phase-2",
  "emaar-the-88-vs-m3m-crown-phase-1",
  "emaar-the-88-vs-puri-diplomatic-residences",
  "emaar-the-88-vs-smartworld-sky-arc",
  "emaar-the-88-vs-sobha-city-phase-6",
  "emaar-urban-oasis-phase-1-2-vs-m3m-trump-towers-1",
  "emaar-urban-oasis-phase-4-vs-m3m-golf-hills-phase-2",
  "emaar-urban-oasis-phase-4-vs-sobha-city-phase-6",
  "m3m-altitude-vs-m3m-capital-phase-2",
  "m3m-altitude-vs-oberoi-realty-360-north",
  "m3m-altitude-vs-puri-diplomatic-residences",
  "m3m-altitude-vs-smartworld-one-dxp",
  "m3m-capital-phase-2-vs-m3m-golf-hills-phase-2",
  "m3m-capital-phase-2-vs-smartworld-one-dxp",
  "m3m-crown-phase-1-vs-oberoi-realty-360-north",
  "m3m-golf-hills-phase-1-vs-oberoi-realty-360-north",
  "m3m-golf-hills-phase-1-vs-signature-global-de-luxe-dxp",
  "m3m-golf-hills-phase-2-vs-signature-global-titanium-spr",
  "m3m-mansion-phase-1-vs-m3m-trump-towers-1",
  "m3m-mansion-phase-1-vs-oberoi-realty-360-north",
  "m3m-trump-towers-1-vs-oberoi-realty-360-north",
  "m3m-trump-towers-1-vs-puri-the-aravallis",
  "m3m-trump-towers-1-vs-smartworld-sky-arc",
  "oberoi-realty-360-north-vs-signature-global-de-luxe-dxp",
  "oberoi-realty-360-north-vs-sobha-city-phase-5",
  "puri-diplomatic-residences-vs-smartworld-one-dxp",
  "puri-diplomatic-residences-vs-sobha-city-phase-5",
  "signature-global-titanium-spr-vs-smartworld-sky-arc",
  "smartworld-one-dxp-phase-2-vs-sobha-city-phase-5",
]);
